# constants.py

ROWS = 20
COLS = 20
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60

# --- MODIFIKASI INI ---
BUILDABLE_TILE_ID = 0
PATH_TILE_ID = 1
START_TILE_ID = 2
END_TILE_ID = 3
# --- AKHIR MODIFIKASI ---

TURRET_LEVELS = 4
ANIMATION_STEPS = 8
ANIMATION_DELAY = 16

TURRET_COST = 100
ENEMY_REWARD = 25